version: '3'

services:
  api:
    build: .
    container_name: product-catalog
    volumes:
      - .:/product-catalog
    ports:
      - "8000:8000"
    network_mode: "host"
    restart: unless-stopped 
